### ISSUE TITLE
Incorrect/Missing CuP plugin used

### ISSUE THREAD

**Issue by asos-edgeorge** [KodeinKoders/CuP-Presentation-Template#1]
Firstly, congratulations on launching CuP! ✨

The talk at Android Makers was really well executed and showed how much time/effort has been put into this project. It was so great to see and I am very excited to give this a try, _but_ having pulled this repo it looks like the plugin defined here is incorrect (or doesn't yet exist).

https://github.com/KodeinKoders/CuP-Presentation-Template/blob/841ff0072b87b9650bd6fe333b6a8bac0ea1ed3d/build.gradle.kts#L4

The documentation on the main repo references `org.kodein.pres.cup` as the correct plugin - but neither of these seem to be available via Gradle's plugin repo yet.

Does this plugin need to be published and if so, which is the correct one?]

Congrats once again - can't wait to get started using this

**Comment by SalomonBrys** [comment]
The documentation is incorrect. 
The correct plugin is indeed `net.kodein.cup`.
Neither the plugin not the cup artifacts have been published (to the Gradle plugin portal or to Maven Central) yet.
As we just open sources the project, we could not publish the artifact before the open sourcing.
We will publish the artifacts next week.
In the meantime, you can run `./gradlew publishToMavenLocal` on [CuP](https://github.com/KodeinKoders/CuP) and this template project should work out of the box.

**Comment by asos-edgeorge** [comment]
Nice one and sorry for being a little keen! I can confirm that running `./gradlew publishToMavenLocal` on each relevant folder within the main CuP project worked just fine

<img width="750" src="https://github.com/KodeinKoders/CuP-Presentation-Template/assets/84779237/9ef09d60-e2f7-48ba-baa2-7cba32dfc141">

Thanks a lot!
